### ISSUE TITLE
weird black boxes and gitches. also the full window doesn't show.

### ISSUE THREAD

**Issue by ingenarel** [MarcosTypeAP/color-picker.nvim#1]
![1](https://github.com/user-attachments/assets/368183bf-0d09-446c-9d5d-7cdd87038836)
![2](https://github.com/user-attachments/assets/178eb361-4e83-4284-82d5-9e19178c6e0a)
![3](https://github.com/user-attachments/assets/8a721840-c288-441c-95d3-d15d2425e3a7)

i need to scroll down to see the window:
![4](https://github.com/user-attachments/assets/1e6537f7-9265-4440-a101-d6aa5cae2e40)

i'm using windows 10 terminal, haven't tried it in any linux terminal yet because i'm currently stuck in windows.

i installed neovim through scoop, using the nightly version:
```
NVIM v0.11.0-dev-851+g4f9311b75
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
```

**Comment by MarcosTypeAP** [comment]
Hi! Thanks for sharing! Testing I found that shifting the hue (updating the highlight groups) leads to artifacts on large pallets, and also if you continue shifting, at some point starts becoming a memory leak (don't know how). This plugin is intended to be a small-medium size pallet, and the problem seems to be with how highlight groups work, so I will just close this and call it a day :+1:
